development:
  adapter: postgresql
  database: findpie_dev
  username: root
  password: root
  host: localhost

test:
  adapter: postgresql
  database: findpie_test
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  database: findpie_live
  username: root
  password: root
  host: localhost